USE [bible]
GO
/****** Object:  Table [dbo].[key_abbreviations_english] - A table mapping book abbreviations to the book they refer to ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[key_abbreviations_english]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[key_abbreviations_english](
	[id] [int] IDENTITY(1,1) NOT NULL, -- Abbreviation ID
	[a] [nvarchar](max) NOT NULL, 
	[b] [int] NOT NULL, -- ID of book that is abbreviated
	[p] [bit] NOT NULL, -- Whether an abbreviation is the primary one for the book
 CONSTRAINT [PK_key_abbreviations_english] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
END
GO
SET IDENTITY_INSERT [dbo].[key_abbreviations_english] ON 

INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (1, N'Gen', 1, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (2, N'Ge', 1, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (3, N'Gn', 1, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (4, N'Exo', 2, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (5, N'Ex', 2, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (6, N'Exod', 2, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (7, N'Lev', 3, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (8, N'Le', 3, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (9, N'Lv', 3, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (10, N'Num', 4, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (11, N'Nu', 4, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (12, N'Nm', 4, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (13, N'Nb', 4, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (14, N'Deut', 5, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (15, N'Dt', 5, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (16, N'Josh', 6, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (17, N'Jos', 6, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (18, N'Jsh', 6, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (19, N'Judg', 7, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (20, N'Jdg', 7, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (21, N'Jg', 7, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (22, N'Jdgs', 7, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (23, N'Rth', 8, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (24, N'Ru', 8, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (25, N'1 Sam', 9, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (26, N'1 Sa', 9, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (27, N'1Samuel', 9, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (28, N'1S', 9, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (29, N'I Sa', 9, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (30, N'1 Sm', 9, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (31, N'1Sa', 9, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (32, N'I Sam', 9, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (33, N'1Sam', 9, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (34, N'I Samuel', 9, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (35, N'1st Samuel', 9, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (36, N'First Samuel', 9, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (37, N'2 Sam', 10, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (38, N'2 Sa', 10, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (39, N'2S', 10, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (40, N'II Sa', 10, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (41, N'2 Sm', 10, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (42, N'2Sa', 10, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (43, N'II Sam', 10, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (44, N'2Sam', 10, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (45, N'II Samuel', 10, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (46, N'2Samuel', 10, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (47, N'2nd Samuel', 10, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (48, N'Second Samuel', 10, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (49, N'1 Kgs', 11, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (50, N'1 Ki', 11, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (51, N'1K', 11, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (52, N'I Kgs', 11, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (53, N'1Kgs', 11, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (54, N'I Ki', 11, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (55, N'1Ki', 11, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (56, N'I Kings', 11, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (57, N'1Kings', 11, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (58, N'1st Kgs', 11, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (59, N'1st Kings', 11, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (60, N'First Kings', 11, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (61, N'First Kgs', 11, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (62, N'1Kin', 11, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (63, N'2 Kgs', 12, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (64, N'2 Ki', 12, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (65, N'2K', 12, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (66, N'II Kgs', 12, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (67, N'2Kgs', 12, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (68, N'II Ki', 12, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (69, N'2Ki', 12, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (70, N'II Kings', 12, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (71, N'2Kings', 12, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (72, N'2nd Kgs', 12, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (73, N'2nd Kings', 12, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (74, N'Second Kings', 12, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (75, N'Second Kgs', 12, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (76, N'2Kin', 12, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (77, N'1 Chron', 13, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (78, N'1 Ch', 13, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (79, N'I Ch', 13, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (80, N'1Ch', 13, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (81, N'1 Chr', 13, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (82, N'I Chr', 13, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (83, N'1Chr', 13, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (84, N'I Chron', 13, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (85, N'1Chron', 13, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (86, N'I Chronicles', 13, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (87, N'1Chronicles', 13, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (88, N'1st Chronicles', 13, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (89, N'First Chronicles', 13, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (90, N'2 Chron', 14, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (91, N'2 Ch', 14, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (92, N'II Ch', 14, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (93, N'2Ch', 14, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (94, N'II Chr', 14, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (95, N'2Chr', 14, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (96, N'II Chron', 14, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (97, N'2Chron', 14, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (98, N'II Chronicles', 14, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (99, N'2Chronicles', 14, 0)
GO
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (100, N'2nd Chronicles', 14, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (101, N'Second Chronicles', 14, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (102, N'Ezra', 15, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (103, N'Ezr', 15, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (104, N'Neh', 16, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (105, N'Ne', 16, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (106, N'Esth', 17, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (107, N'Es', 17, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (108, N'Job', 18, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (109, N'Job', 18, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (110, N'Jb', 18, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (111, N'Pslm', 19, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (112, N'Ps', 19, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (113, N'Psalms', 19, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (114, N'Psa', 19, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (115, N'Psm', 19, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (116, N'Pss', 19, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (117, N'Prov', 20, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (118, N'Pr', 20, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (119, N'Prv', 20, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (120, N'Eccles', 21, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (121, N'Ec', 21, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (122, N'Qoh', 21, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (123, N'Qoheleth', 21, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (124, N'Song', 22, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (125, N'So', 22, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (126, N'Canticle of Canticles', 22, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (127, N'Canticles', 22, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (128, N'Song of Songs', 22, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (129, N'SOS', 22, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (130, N'Isa', 23, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (131, N'Is', 23, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (132, N'Jer', 24, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (133, N'Je', 24, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (134, N'Jr', 24, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (135, N'Lam', 25, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (136, N'La', 25, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (137, N'Ezek', 26, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (138, N'Eze', 26, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (139, N'Ezk', 26, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (140, N'Dan', 27, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (141, N'Da', 27, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (142, N'Dn', 27, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (143, N'Hos', 28, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (144, N'Ho', 28, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (145, N'Joel', 29, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (146, N'Joe', 29, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (147, N'Jl', 29, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (148, N'Amos', 30, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (149, N'Am', 30, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (150, N'Obad', 31, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (151, N'Ob', 31, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (152, N'Jnh', 32, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (153, N'Jon', 32, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (154, N'Micah', 33, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (155, N'Mic', 33, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (156, N'Nah', 34, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (157, N'Na', 34, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (158, N'Hab', 35, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (159, N'Zeph', 36, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (160, N'Zep', 36, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (161, N'Zp', 36, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (162, N'Haggai', 37, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (163, N'Hag', 37, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (164, N'Hg', 37, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (165, N'Zech', 38, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (166, N'Zec', 38, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (167, N'Zc', 38, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (168, N'Mal', 39, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (169, N'Mal', 39, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (170, N'Ml', 39, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (171, N'Matt', 40, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (172, N'Mt', 40, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (173, N'Mrk', 41, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (174, N'Mk', 41, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (175, N'Mr', 41, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (176, N'Luk', 42, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (177, N'Lk', 42, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (178, N'John', 43, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (179, N'Jn', 43, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (180, N'Jhn', 43, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (181, N'Acts', 44, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (182, N'Ac', 44, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (183, N'Rom', 45, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (184, N'Ro', 45, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (185, N'Rm', 45, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (186, N'1 Cor', 46, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (187, N'1 Co', 46, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (188, N'I Co', 46, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (189, N'1Co', 46, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (190, N'I Cor', 46, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (191, N'1Cor', 46, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (192, N'I Corinthians', 46, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (193, N'1Corinthians', 46, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (194, N'1st Corinthians', 46, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (195, N'First Corinthians', 46, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (196, N'2 Cor', 47, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (197, N'2 Co', 47, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (198, N'II Co', 47, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (199, N'2Co', 47, 0)
GO
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (200, N'II Cor', 47, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (201, N'2Cor', 47, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (202, N'II Corinthians', 47, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (203, N'2Corinthians', 47, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (204, N'2nd Corinthians', 47, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (205, N'Second Corinthians', 47, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (206, N'Gal', 48, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (207, N'Ga', 48, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (208, N'Ephes', 49, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (209, N'Eph', 49, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (210, N'Phil', 50, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (211, N'Php', 50, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (212, N'Col', 51, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (213, N'Col', 51, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (214, N'1 Thess', 52, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (215, N'1 Th', 52, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (216, N'I Th', 52, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (217, N'1Th', 52, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (218, N'I Thes', 52, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (219, N'1Thes', 52, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (220, N'I Thess', 52, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (221, N'1Thess', 52, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (222, N'I Thessalonians', 52, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (223, N'1Thessalonians', 52, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (224, N'1st Thessalonians', 52, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (225, N'First Thessalonians', 52, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (226, N'2 Thess', 53, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (227, N'2 Th', 53, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (228, N'II Th', 53, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (229, N'2Th', 53, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (230, N'II Thes', 53, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (231, N'2Thes', 53, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (232, N'II Thess', 53, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (233, N'2Thess', 53, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (234, N'II Thessalonians', 53, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (235, N'2Thessalonians', 53, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (236, N'2nd Thessalonians', 53, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (237, N'Second Thessalonians', 53, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (238, N'1 Tim', 54, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (239, N'1 Ti', 54, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (240, N'I Ti', 54, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (241, N'1Ti', 54, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (242, N'I Tim', 54, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (243, N'1Tim', 54, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (244, N'I Timothy', 54, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (245, N'1Timothy', 54, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (246, N'1st Timothy', 54, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (247, N'First Timothy', 54, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (248, N'2 Tim', 55, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (249, N'2 Ti', 55, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (250, N'II Ti', 55, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (251, N'2Ti', 55, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (252, N'II Tim', 55, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (253, N'2Tim', 55, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (254, N'II Timothy', 55, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (255, N'2Timothy', 55, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (256, N'2nd Timothy', 55, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (257, N'Second Timothy', 55, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (258, N'Titus', 56, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (259, N'Tit', 56, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (260, N'Philem', 57, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (261, N'Phm', 57, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (262, N'Hebrews', 58, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (263, N'Heb', 58, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (264, N'James', 59, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (265, N'Jas', 59, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (266, N'Jm', 59, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (267, N'1 Pet', 60, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (268, N'1 Pe', 60, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (269, N'I Pe', 60, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (270, N'1Pe', 60, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (271, N'I Pet', 60, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (272, N'1Pet', 60, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (273, N'I Pt', 60, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (274, N'1 Pt', 60, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (275, N'1Pt', 60, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (276, N'I Peter', 60, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (277, N'1Peter', 60, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (278, N'1st Peter', 60, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (279, N'First Peter', 60, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (280, N'2 Pet', 61, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (281, N'2 Pe', 61, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (282, N'II Pe', 61, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (283, N'2Pe', 61, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (284, N'II Pet', 61, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (285, N'2Pet', 61, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (286, N'II Pt', 61, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (287, N'2 Pt', 61, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (288, N'2Pt', 61, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (289, N'II Peter', 61, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (290, N'2Peter', 61, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (291, N'2nd Peter', 61, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (292, N'Second Peter', 61, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (293, N'1 John', 62, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (294, N'1 Jn', 62, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (295, N'I Jn', 62, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (296, N'1Jn', 62, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (297, N'I Jo', 62, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (298, N'1Jo', 62, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (299, N'I Joh', 62, 0)
GO
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (300, N'1Joh', 62, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (301, N'I Jhn', 62, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (302, N'1 Jhn', 62, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (303, N'1Jhn', 62, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (304, N'I John', 62, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (305, N'1John', 62, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (306, N'1st John', 62, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (307, N'First John', 62, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (308, N'2 John', 63, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (309, N'2 Jn', 63, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (310, N'II Jn', 63, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (311, N'2Jn', 63, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (312, N'II Jo', 63, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (313, N'2Jo', 63, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (314, N'II Joh', 63, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (315, N'2Joh', 63, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (316, N'II Jhn', 63, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (317, N'2 Jhn', 63, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (318, N'2Jhn', 63, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (319, N'II John', 63, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (320, N'2John', 63, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (321, N'2nd John', 63, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (322, N'Second John', 63, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (323, N'3 John', 64, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (324, N'3 Jn', 64, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (325, N'III Jn', 64, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (326, N'3Jn', 64, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (327, N'III Jo', 64, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (328, N'3Jo', 64, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (329, N'III Joh', 64, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (330, N'3Joh', 64, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (331, N'III Jhn', 64, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (332, N'3 Jhn', 64, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (333, N'3Jhn', 64, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (334, N'III John', 64, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (335, N'3John', 64, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (336, N'3rd John', 64, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (337, N'Third John', 64, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (338, N'Jude', 65, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (339, N'Jud', 65, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (340, N'Rev', 66, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (341, N'Re', 66, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (342, N'The Revelation', 66, 0)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (343, N'Genesis', 1, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (344, N'Exodus', 2, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (345, N'Leviticus', 3, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (346, N'Numbers', 4, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (347, N'Deuteronomy', 5, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (348, N'Joshua', 6, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (349, N'Judges', 7, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (350, N'Ruth', 8, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (351, N'1 Samuel', 9, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (352, N'2 Samuel', 10, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (353, N'1 Kings', 11, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (354, N'2 Kings', 12, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (355, N'1 Chronicles', 13, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (356, N'2 Chronicles', 14, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (357, N'Ezra', 15, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (358, N'Nehemiah', 16, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (359, N'Esther', 17, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (360, N'Job', 18, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (361, N'Psalms', 19, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (362, N'Psalm', 19, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (363, N'Proverbs', 20, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (364, N'Ecclesiastes', 21, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (365, N'Song of Solomon', 22, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (366, N'Isaiah', 23, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (367, N'Jeremiah', 24, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (368, N'Lamentations', 25, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (369, N'Ezekiel', 26, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (370, N'Daniel', 27, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (371, N'Hosea', 28, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (372, N'Joel', 29, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (373, N'Amos', 30, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (374, N'Obadiah', 31, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (375, N'Jonah', 32, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (376, N'Micah', 33, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (377, N'Nahum', 34, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (378, N'Habakkuk', 35, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (379, N'Zephaniah', 36, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (380, N'Haggai', 37, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (381, N'Zechariah', 38, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (382, N'Malachi', 39, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (383, N'Matthew', 40, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (384, N'Mark', 41, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (385, N'Luke', 42, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (386, N'John', 43, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (387, N'Acts', 44, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (388, N'Romans', 45, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (389, N'1 Corinthians', 46, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (390, N'2 Corinthians', 47, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (391, N'Galatians', 48, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (392, N'Ephesians', 49, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (393, N'Philippians', 50, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (394, N'Colossians', 51, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (395, N'1 Thessalonians', 52, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (396, N'2 Thessalonians', 53, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (397, N'1 Timothy', 54, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (398, N'2 Timothy', 55, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (399, N'Titus', 56, 1)
GO
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (400, N'Philemon', 57, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (401, N'Hebrews', 58, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (402, N'James', 59, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (403, N'1 Peter', 60, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (404, N'2 Peter', 61, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (405, N'1 John', 62, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (406, N'2 John', 63, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (407, N'3 John', 64, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (408, N'Jude', 65, 1)
INSERT [dbo].[key_abbreviations_english] ([id], [a], [b], [p]) VALUES (409, N'Revelation', 66, 1)
SET IDENTITY_INSERT [dbo].[key_abbreviations_english] OFF